### ISSUE TITLE
Could not find configuration file provided by "opencv_calib3d" when building ros1_bridge 

### ISSUE THREAD

**Issue by destkk** [osrf/rmf_core_ros1_msgs#1]
Operating System: Ubuntu 20.04
DDS Implementation CycloneDDS.

Hi there. I have tried building ros1_bridge based on the instructions but I am facing an issue (see issue below) after executing colcon build --packages-select ros1_bridge --cmake-force-configure.

I have git clone this repo into my ros1 workspace. And I want to bridge both ros1 and ros2 rmf msgs.

```
Starting >>> ros1_bridge
--- stderr: ros1_bridge                         
CMake Error at /opt/ros/foxy/share/theora_image_transport/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
  By not providing "Findopencv_calib3d.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "opencv_calib3d", but CMake did not find one.

  Could not find a package configuration file provided by "opencv_calib3d"
  with any of the following names:

    opencv_calib3dConfig.cmake
    opencv_calib3d-config.cmake

  Add the installation prefix of "opencv_calib3d" to CMAKE_PREFIX_PATH or set
  "opencv_calib3d_DIR" to a directory containing one of the above files.  If
  "opencv_calib3d" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /opt/ros/foxy/share/theora_image_transport/cmake/theora_image_transportConfig.cmake:41 (include)
  CMakeLists.txt:97 (find_package)


---
Failed   <<< ros1_bridge [2.92s, exited with code 1]

Summary: 0 packages finished [3.05s]
  1 package failed: ros1_bridge
  1 package had stderr output: ros1_bridge
```
Does anyone know how to resolve this issue? Thanks in advance.

**Comment by aaronchongth** [comment]
Hello! It looks like a missing dependency on your platform, could you tell me what are the steps you took to build it, what packages you have in your workspace?

As a sanity check, please try a clean build as well, `rm -rf build install log`, then try building up-to the package, `colcon build --packages-up-to ros1_brdige`. I am unsure why `--cmake-force-configure` is required.

An important note, this repository has actually been deprecated and is currently not being kept up to speed with the rest of the RMF development. I apologize for not archiving this repository earlier, please refer to the new message definitions in https://github.com/open-rmf/rmf_internal_msgs

I will go ahead and archive this repository as well as close this issue, please redirect any other questions in the new discussion section here, https://github.com/open-rmf/rmf/discussions
